{
 "title": "Spark Dashboard",
 "tags": [ "spark" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "spark_cluster",
    "label": "Spark Cluster",
    "query": {
     "query": "label_values(metrics_spark_app_driver_DAGScheduler_job_allJobs_Number,spark_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_driver_DAGScheduler_job_allJobs_type_gauges{group=\"spark\", instance=\"spark-master:8085\", job=\"spark-driver\"}) without (app_id)"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_driver_DAGScheduler_job_activeJobs_type_gauges{group=\"spark\", instance=\"spark-master:8085\", job=\"spark-driver\"}) without (app_id)"
    }
   ]
  },
  {
   "title": "No Of Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_master_workers_type_gauges{group=\"spark\", instance=\"master\", job=\"spark-master\"})",
     "legendFormat": "maxMem_MB"
    }
   ]
  },
  {
   "title": "No Of Alive Workers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_master_aliveWorkers_type_gauges{group=\"spark\", instance=\"master\", job=\"spark-master\"})",
     "legendFormat": "maxMem_MB"
    }
   ]
  },
  {
   "title": "No Of Cores Free By Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_worker_coresFree_type_gauges{group=\"spark\", job=\"spark-worker\"}) without (instance)",
     "legendFormat": "maxMem_MB"
    }
   ]
  },
  {
   "title": "No Of Cores Used By Worker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spark_worker_coresUsed_type_gauges{group=\"spark\", job=\"spark-worker\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Spark Driver Running Stages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spark_driver_DAGScheduler_stage_runningStages_type_gauges) without (app_id)",
     "legendFormat": "Running Stages"
    },
    {
     "expr": "sum(spark_driver_DAGScheduler_stage_waitingStages_type_gauges) without (app_id)",
     "legendFormat": "Waiting Stages"
    },
    {
     "expr": "sum(spark_driver_DAGScheduler_stage_failedStages_type_gauges) without (app_id)",
     "legendFormat": "Failed Stages"
    }
   ]
  },
  {
   "title": "Message Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metrics_app_driver_DAGScheduler_messageProcessingTime_Max{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "metrics_app_driver_DAGScheduler_messageProcessingTime_Min{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "metrics_app_driver_DAGScheduler_messageProcessingTime_Mean{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "metrics_app_driver_DAGScheduler_messageProcessingTime_StdDev{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "StdDev"
    }
   ]
  },
  {
   "title": "BlockManager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metrics_app_driver_BlockManager_memory_maxMem_MB_Number{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"gauges\"}",
     "legendFormat": "maxMem_MB"
    },
    {
     "expr": "metrics_app_driver_BlockManager_disk_diskSpaceUsed_MB_Number{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"gauges\"}",
     "legendFormat": "diskSpaceUsed_MB"
    },
    {
     "expr": "metrics_app_driver_BlockManager_memory_maxOnHeapMem_MB_Number{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"gauges\"}",
     "legendFormat": "maxOnHeapMem_MB"
    },
    {
     "expr": "metrics_app_driver_BlockManager_memory_maxOffHeapMem_MB_Number{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"gauges\"}",
     "legendFormat": "maxOffHeapMem_MB"
    }
   ]
  },
  {
   "title": "Memory Free/Used by Worker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(spark_worker_memFree_MB_type_gauges{group=\"spark\", job=\"spark-worker\"}) without (instance)",
     "legendFormat": "memFree_MB"
    },
    {
     "expr": "sum(spark_worker_memUsed_MB_type_gauges{group=\"spark\", job=\"spark-worker\"}) without (instance)",
     "legendFormat": "memUsed_MB"
    }
   ]
  },
  {
   "title": "LiveListenerBus listenerProcessingTime HeartbeatReceiver",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metrics_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Count{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Count"
    },
    {
     "expr": "metrics_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Max{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "metrics_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Mean{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "metrics_app_driver_LiveListenerBus_listenerProcessingTime_org_apache_spark_HeartbeatReceiver_Min{group=\"spark\", instance=\"application\", job=\"spark-application\", type=\"timers\"}",
     "legendFormat": "Min"
    }
   ]
  }
 ]
}