{
 "title": "Trino Dashboard",
 "description": "Trino deploy on k8s, collect jmx to monitor cluster",
 "tags": [ "trino" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Workers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "trino_failuredetector_name_HeartbeatFailureDetector_ActiveCount{job=\"trino\"}"
      }
     ]
    },
    {
     "title": "Block Workers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_BlockedNodes{job=\"trino\"}"
      }
     ]
    },
    {
     "title": "Available Processors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "trino_memory_name_ClusterMemoryManager_TotalAvailableProcessors{job=\"trino\"}"
      }
     ]
    },
    {
     "title": "Total Distributed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_TotalDistributedBytes{job=\"trino\"}",
       "legendFormat": "current"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_TotalDistributedBytes{job=\"trino\"} offset 1d",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_TotalDistributedBytes{job=\"trino\"} offset 7d",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Free Distributed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_FreeDistributedBytes{job=\"trino\"}",
       "legendFormat": "current"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_FreeDistributedBytes{job=\"trino\"} offset 1d",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_FreeDistributedBytes{job=\"trino\"} offset 7d",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Reserved Revocable Distributed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedRevocableDistributedBytes{job=\"trino\"}",
       "legendFormat": "current"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedRevocableDistributedBytes{job=\"trino\"} offset 1d",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedRevocableDistributedBytes{job=\"trino\"} offset 7d",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Reserved Distributed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedDistributedBytes{job=\"trino\"}",
       "legendFormat": "current"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedDistributedBytes{job=\"trino\"} offset 1d",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "trino_memory_type_ClusterMemoryPool_name_general_ReservedDistributedBytes{job=\"trino\"} offset 7d",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Cluster User Memory Reservation (All Running Queries)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_name_ClusterMemoryManager_ClusterUserMemoryReservation{job=\"trino\"}",
       "legendFormat": "current"
      },
      {
       "expr": "trino_memory_name_ClusterMemoryManager_ClusterUserMemoryReservation{job=\"trino\"} offset 1d",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "trino_memory_name_ClusterMemoryManager_ClusterUserMemoryReservation{job=\"trino\"} offset 7d",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Cluster Total Memory Reservation (All Running Queries)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "trino_memory_name_ClusterMemoryManager_ClusterTotalMemoryReservation{job=\"trino\"}",
       "legendFormat": "current"
      },
      {
       "expr": "trino_memory_name_ClusterMemoryManager_ClusterTotalMemoryReservation{job=\"trino\"} offset 1d",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "trino_memory_name_ClusterMemoryManager_ClusterTotalMemoryReservation{job=\"trino\"} offset 7d",
       "legendFormat": "1 week ago"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Execution Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running Queries",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "trino_execution_name_QueryManager_RunningQueries{job=\"trino\"}"
      }
     ]
    },
    {
     "title": "Queued Queries",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "trino_execution_name_QueryManager_QueuedQueries{job=\"trino\"}"
      }
     ]
    },
    {
     "title": "Number of queries submitted per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_memory_type_ClusterMemoryPool_name_general_AssignedQueries{job=\"trino\"}[1m])",
       "legendFormat": "current"
      },
      {
       "expr": "increase(trino_memory_type_ClusterMemoryPool_name_general_AssignedQueries{job=\"trino\"}[1m] offset 1d)  ",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "increase(trino_memory_type_ClusterMemoryPool_name_general_AssignedQueries{job=\"trino\"}[1m] offset 7d) ",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Number of queries completed per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_memory_type_ClusterMemoryPool_name_general_AssignedQueries{job=\"trino\"}[1m])",
       "legendFormat": "current"
      },
      {
       "expr": "increase(trino_memory_type_ClusterMemoryPool_name_general_AssignedQueries{job=\"trino\"}[1m] offset 1d)",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "increase(trino_memory_type_ClusterMemoryPool_name_general_AssignedQueries{job=\"trino\"}[1m] offset 7d)",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Number of failed queries per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "targets": [
      {
       "expr": "increase(trino_execution_name_SqlTaskManager_FailedTasks{job=\"trino\"}[1m])",
       "legendFormat": "current"
      },
      {
       "expr": "increase(trino_execution_name_SqlTaskManager_FailedTasks{job=\"trino\"}[1m] offset 1d)",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "increase(trino_execution_name_SqlTaskManager_FailedTasks{job=\"trino\"}[1m] offset 7d)",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "Total number of queries with memory leaks per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "increase(trino_memory_name_ClusterMemoryManager_NumberOfLeakedQueries{job=\"trino\"}[1m])",
       "legendFormat": "current"
      },
      {
       "expr": "increase(trino_memory_name_ClusterMemoryManager_NumberOfLeakedQueries{job=\"trino\"}[1m] offset 1d)",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "increase(trino_memory_name_ClusterMemoryManager_NumberOfLeakedQueries{job=\"trino\"}[1m] offset 7d)",
       "legendFormat": "1 week ago"
      }
     ]
    },
    {
     "title": "The total number of queries killed by OOM per minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "increase(trino_memory_name_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{job=\"trino\"}[1m])",
       "legendFormat": "current"
      },
      {
       "expr": "increase(trino_memory_name_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{job=\"trino\"}[1m] offset 1d)",
       "legendFormat": "1 day ago"
      },
      {
       "expr": "increase(trino_memory_name_ClusterMemoryManager_QueriesKilledDueToOutOfMemory{job=\"trino\"}[1m] offset 7d)",
       "legendFormat": "1 week ago"
      }
     ]
    }
   ]
  }
 ]
}