global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: zookeeper
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["zookeeper-1:9200", "zookeeper-2:9200", "zookeeper-3:9200"]

  - job_name: kafka
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets: ["kafka-1:9200", "kafka-2:9200", "kafka-3:9200"]

  - job_name: kafka-schema-registry
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["schema-registry:9200"]

  - job_name: kafka-connect
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["connect:9200"]

  - job_name: spark-master
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["spark-master:8084"]
        labels:
          group: "spark"
          instance: "master"

  - job_name: spark-worker
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["spark-worker-1:7071", "spark-worker-2:7072", "spark-worker-3:7073"]
        labels:
          group: "spark"

  - job_name: spark-driver
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["spark-master:8085"]
        labels:
          group: "spark"

  - job_name: spark-executor
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["spark-worker-1:7070", "spark-worker-2:7070", "spark-worker-3:7070"]
        labels:
          group: "spark"

  - job_name: spark-application
    scrape_interval: 10s
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["spark-master:4048"]
        labels:
          group: "spark"
          instance: "application"
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: metrics_app_[^_]+_[^_]+_(.*)
        target_label: __name__
        replacement: metrics_app_${1}

  - job_name: full-offset
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    static_configs: 
      - targets: ["spark-master:8086"]
        labels:
          group: "offset"

  - job_name: minio-cluster
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ["minio1:9000", "minio2:9000", "minio3:9000"]
        labels:
          group: "minio"
          instance: "cluster"

  - job_name: minio-bucket
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
      - targets: ["minio1:9000", "minio2:9000", "minio3:9000"]
        labels:
          group: "minio"
          instance: "bucket"

  - job_name: minio-node
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
      - targets: ["minio1:9000", "minio2:9000", "minio3:9000"]
        labels:
          group: "minio"

  - job_name: minio-resource
    metrics_path: /minio/v2/metrics/resource
    scheme: http
    static_configs:
      - targets: ["minio1:9000", "minio2:9000", "minio3:9000"]
        labels:
          group: "minio"
          instance: "resource"

  - job_name: trino
    metrics_path: /metrics
    static_configs:
      - targets: ["trino:8889"]
    basic_auth:
      username: admin
      password:

  - job_name: trino-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["trino-worker-1:8889", "trino-worker-2:8889"]
    basic_auth:
      username: admin
      password:
