groups:
  - name: KafkaAlerts
    interval: 15s
    rules:
      - alert: BrokerNotInNormalState
        expr: kafka_server_kafkaserver_brokerstate != 3
        for: 60s
        labels:
          severity: critical
        annotations:
          summary: "Broker {{ $labels.instance }} is not in normal state"
          description: "Broker {{ $labels.instance }}'s state is {{ $value }}, please check and restart if needed"

      - alert: BrokerOverload
        expr: kafka_server_brokertopicmetrics_failedproducerequests_total > 0 or kafka_server_brokertopicmetrics_failedfetchrequests_total > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Kafka broker is failing to handle produce or fetch requests"
          description: |
            Broker {{ $labels.instance }} is reporting failed produce or fetch requests.
            This could indicate performance degradation, I/O issues, full disk, under-replicated partitions, or pressure from clients.
            Check broker logs, monitor system resources (CPU, memory, disk, network), and investigate client-side errors to identify root causes.

      - alert: KafkaBrokerDown
        expr: count(kafka_server_replicamanager_leadercount{job="kafka"}) < 3
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "Kafka broker is down"
          description: "One or more Kafka brokers are down"
