groups:
  - name: MinIOAlerts
    interval: 15s
    rules:
      # Cluster Health Alerts
      - alert: MinIOClusterUnhealthy
        expr: minio_cluster_health_status{job="minio"} != 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MinIO cluster is unhealthy"
          description: "MinIO cluster health status is not normal. Check cluster logs and node health."

      - alert: MinIONodesOffline
        expr: minio_cluster_nodes_offline_total{job="minio"} > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MinIO nodes are offline"
          description: "{{ $value }} MinIO node(s) are offline. Check node health and network connectivity."

      - alert: MinIODrivesOffline
        expr: minio_cluster_drive_offline_total{job="minio"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "MinIO drives are offline"
          description: "{{ $value }} drive(s) are offline. Check drive connections and health."

      # Resource Usage Alerts
      - alert: MinIOLowStorage
        expr: minio_cluster_capacity_raw_free_bytes{job="minio"} / minio_cluster_capacity_raw_total_bytes{job="minio"} < 0.2
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Low storage capacity"
          description: "MinIO cluster has less than 20% free storage. Consider expanding storage capacity."

      - alert: MinIOHighMemoryUsage
        expr: minio_node_mem_used_perc{job="minio"} > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "MinIO node {{ $labels.instance }} memory usage is above 80%. Consider adding more RAM or optimizing memory usage."

      - alert: MinIOHighCPULoad
        expr: minio_node_cpu_avg_load15{job="minio"} > 80
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High CPU load"
          description: "MinIO node {{ $labels.instance }} CPU load is above 80%. Consider adding more CPU resources or optimizing load."

      # Drive Health Alerts
      - alert: MinIODriveErrors
        expr: minio_node_drive_errors_ioerror{job="minio"} > 0 or minio_node_drive_errors_timeout{job="minio"} > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Drive errors detected"
          description: "MinIO node {{ $labels.instance }} has drive errors. Check drive health and connections."

      - alert: MinIOHighDriveLatency
        expr: minio_node_drive_latency_us{job="minio"} > 1000
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High drive latency"
          description: "MinIO node {{ $labels.instance }} has high drive latency. Check drive performance."

      # Network Alerts
      - alert: MinIONetworkErrors
        expr: minio_node_if_rx_errors{job="minio"} > 0 or minio_node_if_tx_errors{job="minio"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Network errors detected"
          description: "MinIO node {{ $labels.instance }} has network errors. Check network connectivity."

      - alert: MinIOInterNodeErrors
        expr: minio_inter_node_traffic_errors_total{job="minio"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Inter-node communication errors"
          description: "MinIO cluster has inter-node communication errors. Check internal network."

      # Replication Alerts
      - alert: MinIOReplicationErrors
        expr: minio_bucket_replication_proxied_get_requests_failures{job="minio"} > 0 or minio_bucket_replication_proxied_put_tagging_requests_failures{job="minio"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Replication errors detected"
          description: "MinIO has replication errors. Check replication configuration and network."

      - alert: MinIOHighReplicationBacklog
        expr: minio_node_replication_recent_backlog_count{job="minio"} > 1000
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High replication backlog"
          description: "MinIO has high replication backlog. Check replication performance and configuration."
