groups:
  - name: MinIOAlerts
    interval: 15s
    rules:
      # Cluster Health Alerts
      - alert: MinIOClusterUnhealthy
        expr: minio_cluster_health_status{job="minio-cluster"} != 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MinIO cluster is unhealthy"
          description: "MinIO cluster health status is not normal. Check cluster logs and node health."

      - alert: MinIONodesOffline
        expr: minio_cluster_nodes_offline_total{job="minio-cluster"} > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "MinIO nodes are offline"
          description: "{{ $value }} MinIO node(s) are offline. Check node health and network connectivity."

      - alert: MinIODrivesOffline
        expr: minio_cluster_drive_offline_total{job="minio-cluster"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "MinIO drives are offline"
          description: "{{ $value }} drive(s) are offline. Check drive connections and health."

      # Drive Health Alerts
      - alert: MinIODriveErrors
        expr: minio_node_drive_errors_ioerror{job="minio-node"} > 0 or minio_node_drive_errors_timeout{job="minio-node"} > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Drive errors detected"
          description: "MinIO node {{ $labels.server }} has drive errors. Check drive health and connections."

      # Network Alerts
      - alert: MinIONetworkErrors
        expr: minio_node_if_rx_errors{job="minio-resource"} > 0 or minio_node_if_tx_errors{job="minio-resource"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Network errors detected"
          description: "MinIO node {{ $labels.server }} has network errors. Check network connectivity."

      - alert: MinIOInterNodeErrors
        expr: minio_inter_node_traffic_errors_total{job="minio-cluster"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Inter-node communication errors"
          description: "MinIO cluster has inter-node communication errors. Check internal network."

      # Replication Alerts
      - alert: MinIOReplicationErrors
        expr: minio_bucket_replication_proxied_get_requests_failures{job="minio-bucket"} > 0 or minio_bucket_replication_proxied_put_tagging_requests_failures{job="minio-bucket"} > 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Replication errors detected"
          description: "MinIO has replication errors. Check replication configuration and network."
