groups:
  - name: SparkAlerts
    interval: 15s
    rules:
      - alert: JVMHeapResourceExhaustion
        expr: sum(spark_driver_jvm_heap_usage_type_gauges{group="spark", instance="spark-master:8085", job="spark-driver"}) without (app_id) > 0.85
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "JVM Heap Full"
          description: "Detects heap overflow risk, causing OutOfMemoryError"

      - alert: ZeroActiveWorker
        expr: sum(spark_master_aliveWorkers_type_gauges{group="spark", instance="master", job="spark-master"}) == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "No Active Spark Worker"
          description: "Spark Cluster has 0 worker for 30 seconds"

      - alert: LiveListenerBusEventGotDropped
        expr: metrics_app_driver_livelistenerbus_queue_appstatus_numdroppedevents_type_counters_total > 0 or metrics_app_driver_livelistenerbus_queue_eventlog_numdroppedevents_type_counters_total > 0
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: "Event got dropped"
          description: "Driver overloaded due to handling too many events, some events were missing"
